const state = { filter: '7days', jobs: [], sort: { key: 'posted_date', asc: false }, page: 1, pageSize: 12, runId: null };
const $ = (id) => document.getElementById(id);
const statNames = {job_cards_discovered:'Jobs discovered',valid_linkedin_urls:'Valid LinkedIn URLs',unique_jobs:'Unique jobs',jobs_within_date_range:'Jobs in date range',new_jobs_added:'New jobs added',validation_failures:'Validation failures',duplicates_removed:'Duplicates removed',existing_jobs_skipped:'Existing jobs skipped'};

function setStatus(status) { const el=$('status'); const labels={ready:'Ready',running:'Running',completed:'Completed',failed:'Error'}; el.className=`status ${status === 'failed' ? 'error' : status}`; el.innerHTML=`<i></i> ${labels[status] || 'Ready'}`; }
function formatDate(value) { if (!value) return '—'; const d = new Date(`${value.slice(0,10)}T00:00:00`); return Number.isNaN(d) ? value : d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}); }
function setLastRun(run) { $('lastRun').textContent = `Last Run: ${run?.completed_at || run?.started_at ? new Date(run.completed_at || run.started_at).toLocaleString() : '—'}`; }
function showStats(stats) { const section=$('statsSection'); if (!stats) return section.classList.add('hidden'); section.innerHTML=Object.entries(statNames).filter(([key]) => ['job_cards_discovered','valid_linkedin_urls','unique_jobs','jobs_within_date_range','new_jobs_added'].includes(key) || stats[key] > 0).map(([key,label])=>`<article class="stat"><div class="label">${label}</div><div class="number">${stats[key] ?? 0}</div></article>`).join(''); section.classList.remove('hidden'); }
function setError(run) { const panel=$('errorPanel'); if (!run || run.status !== 'failed') return panel.classList.add('hidden'); $('errorMessage').textContent=run.error || 'The job discovery process encountered an error.'; $('errorDetails').textContent=run.details || 'No additional details were available.'; panel.classList.remove('hidden'); }
async function loadJobs() { const response=await fetch('/api/jobs'); const data=await response.json(); if (!response.ok) throw new Error(data.error || 'Could not load jobs.'); state.jobs=data.jobs; const countries=[...new Set(state.jobs.map(j=>j.country).filter(Boolean))].sort(); $('country').innerHTML='<option value="">All countries</option>'+countries.map(c=>`<option>${escapeHtml(c)}</option>`).join(''); renderTable(); }
function escapeHtml(value) { const el=document.createElement('div'); el.textContent=value; return el.innerHTML; }
function filteredJobs() { const query=$('search').value.trim().toLowerCase(), country=$('country').value; return state.jobs.filter(job=>(!query || `${job.title} ${job.country}`.toLowerCase().includes(query)) && (!country || job.country===country)).sort((a,b)=>{const va=(a[state.sort.key]||'').toLowerCase(),vb=(b[state.sort.key]||'').toLowerCase(); return (va>vb?1:va<vb?-1:0)*(state.sort.asc?1:-1);}); }
function renderTable() { const jobs=filteredJobs(), start=(state.page-1)*state.pageSize, rows=jobs.slice(start,start+state.pageSize); $('jobCount').textContent=`${jobs.length} ${jobs.length===1?'job':'jobs'} ${jobs.length !== state.jobs.length ? 'matching filters' : 'loaded'}`; const has=state.jobs.length>0; $('emptyState').classList.toggle('hidden',has); $('tableTools').classList.toggle('hidden',!has); $('tableWrap').classList.toggle('hidden',!has); $('pagination').classList.toggle('hidden',!has); $('downloadButton').classList.toggle('disabled',!has); $('downloadButton').setAttribute('aria-disabled',String(!has)); $('jobsBody').innerHTML=rows.length ? rows.map(job=>`<tr><td>${escapeHtml(job.country)}</td><td>${formatDate(job.posted_date)}</td><td>${escapeHtml(job.title)}</td><td><a class="job-link" href="${escapeHtml(job.url)}" target="_blank" rel="noopener noreferrer">View on LinkedIn ↗</a></td></tr>`).join('') : '<tr><td colspan="4" style="text-align:center;color:#667085;padding:32px">No matching jobs found</td></tr>'; const pages=Math.max(1,Math.ceil(jobs.length/state.pageSize)); if(state.page>pages){state.page=pages;return renderTable()} $('pagination').innerHTML=pages>1?`<button ${state.page===1?'disabled':''} data-page="${state.page-1}">Previous</button>${Array.from({length:pages},(_,i)=>`<button class="${i+1===state.page?'active':''}" data-page="${i+1}">${i+1}</button>`).join('')}<button ${state.page===pages?'disabled':''} data-page="${state.page+1}">Next</button>`:''; }
function setRunning(running) { const button=$('runButton'); button.disabled=running; button.classList.toggle('loading',running); document.querySelector('.empty-run').disabled=running; }
async function runTracker() { setRunning(true); $('runMessage').textContent='Running tracker...'; $('errorPanel').classList.add('hidden'); try { const response=await fetch('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filter:state.filter})}); const run=await response.json(); if(!response.ok) throw new Error(run.error || 'Could not start tracker.'); state.runId=run.id; setStatus('running'); setLastRun(run); pollRun(); } catch(error) { setRunning(false); setStatus('failed'); $('runMessage').textContent='Tracker failed'; setError({status:'failed',error:error.message,details:error.message}); } }
async function pollRun() { try { const response=await fetch(`/api/run/${state.runId}`); const run=await response.json(); setStatus(run.status); setLastRun(run); if(run.status==='running'){setTimeout(pollRun,1500);return} setRunning(false); if(run.status==='completed'){ $('runMessage').textContent='Tracker completed successfully'; showStats(run.stats); await loadJobs(); } else { $('runMessage').textContent='Tracker failed'; setError(run); } } catch(error) { setRunning(false); setStatus('failed'); $('runMessage').textContent='Tracker failed'; setError({status:'failed',error:error.message,details:error.message}); } }
async function initialise() { document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{state.filter=button.dataset.filter;document.querySelectorAll('.filter').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});})); $('runButton').addEventListener('click',runTracker); $('.empty-run').addEventListener('click',runTracker); $('search').addEventListener('input',()=>{state.page=1;renderTable()}); $('country').addEventListener('change',()=>{state.page=1;renderTable()}); document.querySelectorAll('th[data-key]').forEach(th=>th.addEventListener('click',()=>{const key=th.dataset.key;state.sort={key,asc:state.sort.key===key?!state.sort.asc:true};renderTable()})); $('pagination').addEventListener('click',event=>{const page=event.target.dataset.page;if(page){state.page=Number(page);renderTable()}}); try { const response=await fetch('/api/status'),status=await response.json(); setStatus(status.status); setLastRun(status.last_run); if(status.last_run?.stats) showStats(status.last_run.stats); if(status.status==='running'&&status.last_run?.id){state.runId=status.last_run.id;setRunning(true);pollRun()} await loadJobs(); } catch(error) { $('runMessage').textContent='Unable to load dashboard data.'; } }
initialise();
